POST http://localhost:8080/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "email": "testing20@gmail.com",
    "password": "testing123",
    "username": "testing123",
    "name": "testing123"
}

###

POST http://localhost:8080/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "testing@gmail.com",
    "password": "testing123",
}

###

// Replace the long string with the token 
// string you get from the HTTP request above.

GET http://localhost:8080/api/users/current HTTP/1.1
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RpbmcyMEBnbWFpbC5jb20iLCJpYXQiOjE2NDc3MzQzMjAsImV4cCI6MTY0NzgyMDcyMH0.Cq4V_noc96AFtNaJz32MbbSca3dHq6FtobDgbfCvUT4

###

POST http://localhost:8080/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "testing@gmail.com",
    "password": "noaaae"
}